### ISSUE TITLE
Doesn't start

### ISSUE THREAD

**Issue by vadimyer** [driusan/de#10]
https://s.vadimyer.com/8871eb90-8e71-4318-bade-db64777456eb.png

With a file or not. Windows 10, go1.6.2.

**Comment by driusan** [comment]
I believe this should be fixed by 4a8c8c3d. Can you update with `go get -u github.com/driusan/de` and let me know if it works?

**Comment by vadimyer** [comment]
Thanks, it starts. But it feels unresponsive, I literally can't do anything lol.
I tried to show that in a gif:
https://s.vadimyer.com/d995907a-60e7-4d5b-a5d5-be3031112012.gif

**Comment by driusan** [comment]
I just went back into Windows and made change e70ba2632d (which I'd been meaning to do anyways) using the version that you say is unresponsive, and de didn't feel unresponsive to me, but I find Windows 10 generally to be unbearably slow even when I'm not doing anything, so it's hard to say if I just didn't notice because of that.

I have a feeling the above commit might fix your issue, because I wouldn't be surprised if allocating screen buffers has different performance under different drivers (or video cards) and it was getting called excessively.

**Comment by vadimyer** [comment]
No, that didn't fixed an issue :(

**Comment by driusan** [comment]
Does 9c882415bc help?

If not, there's one more optimization I can try tonight that I've been meaning to do anyways, but if neither of those work, I might need to see some profiling data to figure out where the bottleneck is.

**Comment by vadimyer** [comment]
Yes it works. It's far more smooth now, though mouse selection still looks a bit like "slowed".

**Comment by driusan** [comment]
b5a37dc19a is the last low-hanging fruit for optimizing the rendering which might improve it a little.

I'm closing this ticket (especially since it was originally about it crashing, not the performance), but if you notice that performance is/becomes unuseable, feel free to open a new ticket.
