### ISSUE TITLE
Chat room?

### ISSUE THREAD

**Issue by josephholsten** [driusan/de#19]
Would you be interested in having a slack room, or a gitter+irc channel? I feel a little silly creating tickets for some of the questions I've got. Slack is probably the most pleasant experience for someone living in the room, but gitter+freenode-irc is a great compromise with history-search, lots of integrations, and open protocols.

**Comment by driusan** [comment]
I'm fine with either. I'm not sure if there's a big enough userbase for a chat room or IRC channel, but if you make one, I'll join it and try and keep an eye on it.

(You can also email me with questions, but I'd prefer something public, since if you have questions, it probably means someone else does too.)

**Comment by driusan** [comment]
@josephholsten I've been hanging out on gophers.slack.com lately, so I just created a #de channel there. Feel free to join me.

**Comment by josephholsten** [comment]
lgtm
