### ISSUE TITLE
./main.go:174: undefined: dewindow

### ISSUE THREAD

**Issue by joeblew99** [driusan/de#38]
am i doing something wrong ?

````
go get -u github.com/driusan/de/...
x-MacBook-Pro:de apple$ go run main.go 
# command-line-arguments
./main.go:174: undefined: dewindow
x-MacBook-Pro:de apple$ 

````

**Comment by shurcooL** [comment]
See https://github.com/driusan/de#installation steps. You should use:

```
go get -u github.com/driusan/de
```

`go run` isn't really meant to be used aside from small testing programs. You're only supplying `main.go` but not other files in the package like `window.go` (where `dewindow` is defined) and `plugins.go`.

It'd work if you did `go run main.go window.go plugins.go`, but I'd suggest just using `go get -u`, or `go build` if you don't want to install the binary to your `GOPATH/bin`, for example:

```
go build -o /tmp/de && /tmp/de
```

**Comment by joeblew99** [comment]
thanks. did not know that.
is it because the root of the repo has a main, and so its automagically puts a compiled exe in the bin ?

doing "de" worked for me. I had the bin in my path.

**Comment by driusan** [comment]
Yes, if you `go get` a main package, Go will automatically put the compiled binary in `$GOBIN` (or `$GOPATH/bin` if `$GOBIN` isn't set. Since the root of this repo is a `main` package, it gets automatically installed. (If the main package wasn't under the root of the repo, you'd have to do `go get -u repo/...` with the three dots telling it to install the subpackages too.)
