### ISSUE TITLE
RFC: Community Plugins

### ISSUE THREAD

**Issue by binary132** [driusan/de#40]
Cool project!  Two thoughts immediately spring to mind.

First, like other resources, I would expect a community portal to a list of plugins, even if it's just a separate repo linked in README.md.

2a, it would be nice to write and distribute plugins in a way independent of the project source.  For example, IntelliJ IDEA plugins aren't distributed and developed as subfolders of the entire IDEA source tree.

2b, that might mean using the new Go plugin package, but it might not.

Hope this was valuable!

**Comment by josephholsten** [comment]
@binary132 I don't actually know of any plugins that are maintained outside of this repo. If you know of some, I'd absolutely love to add them to the README (or a dedicated file if there's enough ;-)

**Comment by driusan** [comment]
sorry for the delay responding @binary132, but like @josephholsten I don't know of any either.

If you create any (or find any), please send a pull request to add them (or email me an I can do it), but at the moment all I know of is the ones that are a core part of `de`, and the proof-of-concept ones in the plugins directory.

**Comment by driusan** [comment]
oh, sorry I forgot to address your other points:

The main problem with the go 1.8+ plugins package is that it's Linux only, and the second related problem is that it requires the plugins to be part of "package main" and built with a special build mode. Taken together, this means that it's not possible to make hybrid plugins that can be imported as a package with an init function on non-Linux systems and dynamically loaded plugins in Linux.

I do intend to eventually look into adding support for them (which from what I've read of the plugins package, shouldn't be too much work), but since I primarily use other unix-like OSes I haven't had a chance yet.

**Comment by binary132** [comment]
Good point re. plugins and Linux -- slipped my mind!  `pie` plugins look potentially cool.
